[package]
authors = ["Roman Kolesnikov <rk2001.mailbox@gmail.com>"]
edition = "2018"
name = "todo"
version = "0.1.0"

[dependencies]
dirs = "3.0"
regex = "1"
serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
subprocess = "0.2.6"
